Algoritmo "Medidas"


Var
     A,B,C, Quadrado, Triangulo, Trapezio : real


Inicio
    escreva("Digite a medida A : ")
    leia(A)
      escreva("Digite a medida B : ")
    leia(B)
      escreva("Digite a medida B : ")
    leia(C)
    Quadrado <- A * A
    Triangulo <- (A * B) / 2
    Trapezio <- (A + B) * C / 2
    escreval("Area do Quadrado = ", Quadrado :8:4)
    escreval("Area do Triangulo  = ", Triangulo :8:4)
    escreval("Area do Trapezio = ", Trapezio :8:4)



Fimalgoritmo