Algoritmo "Retangulo"

Var
  Base,Altura,Area,Perimetro,Diagonal : real


Inicio
   escreva("Base do retângulo: ")
   leia(Base)
   escreva("Altura do retângulo: ")
    leia(Altura)
    Area <- Base * Altura
    Perimetro <- (Base + Altura) *2
    Diagonal <- RaizQ(Exp(base,2) + Exp(altura,2))
     escreval("Area = ", Area :8:4)
     escreval("Perimetro = ", Perimetro :8:4)
     escreval ("Diagonal = ", Diagonal :8:4)

Fimalgoritmo